main:
  children:
    ipsec:

ipsec:
  hosts:
    client:
      psk: "RAhISGgZWd8hMzmRgAQ/KPahbbBxHL/G"
      ansible_host: 10.128.0.101
      ansible_user: kali
      ansible_password: kali
      ansible_become_pass: kali
      ip:
        left: "10.128.0.101"
        left_subnet: "10.128.1.0/24"
        right: "10.128.0.102"
        right_subnet: "10.128.1.0/24"
    server:
      psk: "RAhISGgZWd8hMzmRgAQ/KPahbbBxHL/G"
      ansible_host: 10.128.0.102
      ansible_user: kali
      ansible_password: kali
      ansible_become_pass: kali
      ip:
        left: "10.128.0.102"
        left_subnet: "10.128.1.0/24"
        right: "10.128.0.101"
        right_subnet: "10.128.1.0/24"